// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obctidmxgixxjfegfdag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iY3RpZG14Z2l4eGpmZWdmZGFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDYxNTMsImV4cCI6MjA3MDIyMjE1M30.BjOSCYXlELLysTZ7xvQQW6toTmYyTxWn_PM8sobztTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});